### PR TITLE
Integrated Mapbox to create/update services/stations

### PR DESCRIPTION
**Pull request by shweta2101**
- Integrated Mapbox to enable user to add polygon(geojson) while updating/creating a station/service.
Screenshot 2023-09-26 at 5 40 22 PM
Screenshot 2023-09-26 at 5 41 14 PM
Screenshot 2023-09-26 at 5 43 49 PM

### CODE REVIEW

**Comment by MashB** [comment]
@shweta2101 , please confirm if mapbox gl is free to use library or paid . If possible please share the link about pricing / usage policy.

@susrisha , fyi

**Review by MashB — CHANGES_REQUESTED** [review]
@shweta2101 , please confirm if mapbox gl is free to use library or paid . If possible please share the link about pricing / usage policy.

@susrisha , fyi

**Comment by shweta2101** [comment]
> @shweta2101 , please confirm if mapbox gl is free to use library or paid . If possible please share the link about pricing / usage policy.
> 
> @susrisha , fyi

Hi @MashB , as far as map rendering is concerned, it's free of cost. I'll get back to you on this with more details.

**Comment by shweta2101** [comment]
> > @shweta2101 , please confirm if mapbox gl is free to use library or paid . If possible please share the link about pricing / usage policy.
> > @susrisha , fyi
> 
> Hi @MashB , as far as map rendering is concerned, it's free of cost. I'll get back to you on this with more details.

According to official Mapbox docs:
 
 "You can use Mapbox GL JS in your web applications without incurring direct costs related to rendering maps. However, other Mapbox services and features, such as geocoding, routing, and additional styling options, may have associated costs based on your usage and requirements".

The official mapbox document which was followed while integrating mapbox in current project didn't mention anything related to pricing. But according to the screenshot below (based on our requirement), after 50k loads, there's a cost attached to it. 

 @susrisha , please confirm if the free version meets our requirement. 

Screenshot 2023-09-27 at 12 16 33 PM


Ref: 
- https://docs.mapbox.com/help/troubleshooting/manage-web-map-costs/#interactive-maps
- https://www.mapbox.com/pricing#map-loads-for-web

**Comment by susrisha** [comment]
Not able to comment inline. However, the answer about mapbox is like this
- the rendering of map is free as long as it is on web browser (in this case yes)
- the pricing will come into picture with the geo coding which is only when you try and search for place in the map interface. I am assuming the search will be less than the threshold
- There may be other alternatives for mapbox but this is used extensively across the industry with good support

**Comment by sureshgaussian** [comment]
What happens if you exceed the limit for search?

**Comment by MashB** [comment]
Please explore leafletjs , very known library. Sharing few references for feasibility/evaluation

https://leafletjs.com/examples/geojson/
https://leaflet.github.io/Leaflet.draw/docs/examples/full.html

**Comment by sujata-m** [comment]
@MashB I have worked on LeafletJS and I don't think we can use it here, Leaflet works on x, y  and z tiles (chunks of images of map, that can be in thousands) that we don't have. 

we cannot use it until we have a provision to crop the map images into 256x256, 512x512 and 1024x1024 size

**Pull request merged**
